# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default training settings and hyperparameters for medium-augmentation COCO training
### override
yolo_override:
  task: detect  # YOLO task, i.e. detect, segment, classify, pose
  mode: predict  # YOLO mode, i.e. train, val, predict, export, track, benchmark

  # Train settings -------------------------------------------------------------------------------------------------------
  model: /home/nerc-ningxiao/share/code/OLDT/weights/morrison_mix_single/000000_best.pt # path to model file, i.e. yolov8n.pt, yolov8n.yaml
  data: ./datasets/morrison_mix_single.yaml # path to data file, i.e. coco128.yaml
  verbose: false  # whether to print verbose output


### setup
setup:
  sub_data_dir: morrison_mix_single/000000
  ldt_branches:
    0: 20230923080858branch_ldt_00.pt
  batch_size: 32
  start_epoch: 1
  dataset_format: Mix_VocFormat
  use_data_on_server: true
  flow_file: train_flow.yaml
  server_dataset_dir: /home/nerc-ningxiao/datasets/   # server dataset dir  

### landmark detect settings
max_token_num: 784
pool_size: [24, 24]
use_variable_tokennum: true
normalize_before: false
landmark_num: 24
decoder_num_queries: 96
transformer_d: 384
calc_intermediate: false

### loss
class_loss_w: 1.0
dist_loss_w: 5.0
PN_loss_w: 1.0
rotation_loss_w: 0.0

score_alpha: 0.15
score_beta: 0.4
score_eps: 0.0001

### post progress
models_dir: datasets/morrison_models
pcd_models:
  0: bar_clamp.ply
  1: gearbox.ply
  2: nozzle.ply
  3: part1.ply
  4: part3.ply
  5: pawn.ply
  6: turbine_housing.ply
  7: vase.ply
  8: ape.ply
models_info: models_info.json
default_K: default_K.txt
out_bbox_threshold: 1.0
