1:
  lr_func: warmup
  lr:      0.0001
  cfg:
    use_variable_tokennum: False
40:
  lr_func: cosine
  lr:      0.0001
  cfg:
    use_variable_tokennum: False
200:
  lr_func: warmup
  lr:      0.00012
  cfg:
    use_variable_tokennum: True
240:
  lr_func: cosine
  lr:      0.00012
  cfg:
    use_variable_tokennum: True
600:
