0:
  lr_func: warmup
  lr:      0.0001
  cfg:
    use_variable_tokennum: False
40:
  lr_func: cosine
  lr:      0.0001
  cfg:
    use_variable_tokennum: False
400:

#   lr_func: warmup
#   lr:      0.00015
#   cfg:
#     use_variable_tokennum: True
# 310:
#   lr_func: cosine
#   lr:      0.00015
#   cfg:
#     use_variable_tokennum: True
# 600:
