0:
  lr_func: warmup
  lr:      0.00012
  cfg:
    use_variable_tokennum: False
20:
  lr_func: cosine
  lr:      0.00012
  cfg:
    use_variable_tokennum: False
200:
  lr_func: warmup
  lr:      0.00015
  cfg:
    use_variable_tokennum: True
210:
  lr_func: cosine
  lr:      0.00015
  cfg:
    use_variable_tokennum: True
500:
