0:
  lr_func: warmup
  lr:      0.00008
  cfg:
    use_variable_tokennum: False
40:
  lr_func: cosine
  lr:      0.00008
  cfg:
    use_variable_tokennum: False
200:
  lr_func: warmup
  lr:      0.00012
  cfg:
    use_variable_tokennum: True
220:
  lr_func: cosine
  lr:      0.00012
  cfg:
    use_variable_tokennum: True
500:
